# A minimal left prompt
format = """
$time\
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$spack\
$memory_usage\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$status\
$container\
$shell\
$character"""

# move the rest of the prompt to the right
#right_format = """
#$time"""

[time]
disabled=false
format="[$time]($style) "

[hostname]
#format="[$ssh_symbol$hostname]($style) "

[directory]
truncation_length=0
truncate_to_repo=false
